Webrtc media
BrowserStackCE/webrtc-test-bstack-demo pull request #4
Opened 2022-03-21 21:30 UTC by harsh-git-bs

merging webrtc_media to main

2022-03-21 21:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/BrowserStackCE/webrtc-test-bstack-demo?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/BrowserStackCE/webrtc-test-bstack-demo?pullRequest=4) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: samirans89<br/>:x: harsh-git-bs<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/BrowserStackCE/webrtc-test-bstack-demo?pullRequest=4) it.</sub>

2022-03-22 14:43 UTC, samirans89 requested changes

2022-03-22 14:43 UTC, samirans89 commented on bstack-webrtc-media/src/main/java/WebRTCTestRunner.java
> +                    driver.get("http://" + System.getenv("BROWSERSTACK_USERNAME") +
https

2022-03-22 14:43 UTC, samirans89 commented on bstack-webrtc-media/src/main/java/WebRTCConf.java
> +                    Thread.sleep(30000);
common thread.sleep at the end. see if we can reduce the value.

2022-03-22 14:43 UTC, samirans89 commented on bstack-webrtc-media/src/main/java/WebRTCConf.java
> +                    String[] selections = { "1.1", "1.2", "1.3" };
more intuitive names for the variables
e.g. Chrome_FakeMedia, Chrome_PreExistingMedia, Chrome_UserMedia

2022-03-22 18:25 UTC, harsh-git-bs commented on bstack-webrtc-media/src/main/java/WebRTCTestRunner.java
> +                    driver.get("http://" + System.getenv("BROWSERSTACK_USERNAME") +
done

2022-03-22 18:29 UTC, harsh-git-bs commented on bstack-webrtc-media/src/main/java/WebRTCConf.java
> +                    Thread.sleep(30000);
done

2022-03-22 19:20 UTC, harsh-git-bs commented on bstack-webrtc-media/src/main/java/WebRTCConf.java
> +                    String[] selections = { "1.1", "1.2", "1.3" };
done

2022-03-23 03:38 UTC, samirans89 approved these changes

2022-03-23 03:39 UTC, merged